version: 1
services:
  - type: worker  #Xác định cổng truy cập là worker nè :33
    name: discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true